# GNU sed 4.0.9, compiled by tcc.
#
# The first package built by a shell script rather than a kaem file, which is
# what bash was built for.  The difference is not cosmetic: bash splits a
# variable's value into words, so CC can be one variable holding a compiler
# and its flags, where kaem needed one variable per argument.
#
# 4.0.9 is the last sed that compiles against the Mes C library, and the
# makefile is live-bootstrap's -- sed's own is generated by a configure that
# needs a sed to run.
set -e

# Only the bootstrap's own programs.  Left to itself the builder would add
# /usr/bin, and a makefile that looks up a bare `tcc` or `ar` would find the
# host's -- which on a 64-bit machine fails on this bootstrap's 32-bit objects,
# and, worse, could succeed.
export PATH="$toolPath"

cd "$TMPDIR"
ungz --file "$tarball" --output sed.tar
untar --file sed.tar
cd "sed-$version"

cp "$makefile" Makefile
catm config.h

# This tcc refuses a flag cluster after -ar: it scans every argument for the
# operations it does not support, and "-ar" itself contains an 'a'.
replace --file Makefile --output Makefile.new --match-on '$(AR) cr $@ $^' --replace-with '$(AR) $@ $^'
mv Makefile.new Makefile

make CC="$CC" AR="$AR" LIBC=mes
make install CC="$CC" AR="$AR" PREFIX="$out"

"$out/bin/sed" --version | head -1
