# GNU sed 4.0.9, compiled by tcc.
#
# The first package here built by a shell script rather than a kaem file.
# 4.0.9 is the last version that compiles against the Mes C library, and its
# own Makefile is generated by a configure that needs a sed to run -- so the
# makefile comes from live-bootstrap instead.
{
  derivationWithMeta,
  system,
  platforms,
  stage0,
  tinycc,
  gnumake,
  bash,
  coreutils,
  mesInclude,
}:
let
  pname = "gnused";
  version = "4.0.9";

  fetchurl = import <nix/fetchurl.nix>;
in
derivationWithMeta {
  inherit pname version system;

  tarball = fetchurl {
    url = "https://ftp.gnu.org/gnu/sed/sed-${version}.tar.gz";
    sha256 = "c365874794187f8444e5d22998cd5888ffa47f36def4b77517a808dec27c0600";
  };

  makefile = fetchurl {
    url = "https://raw.githubusercontent.com/fosslinux/live-bootstrap/1bc4296091c51f53a5598050c8956d16e945b0f5/sysa/sed-4.0.9/mk/main.mk";
    name = "main.mk";
    sha256 = "cad7c18d085399d640e23a7feb70b36a378ed7f7dd5053c350f49707622e2e70";
  };

  # What the script may run.  This replaces the PATH the builder would
  # otherwise assemble, which includes the host's /usr/bin.
  toolPath = builtins.concatStringsSep ":" [
    "${coreutils}/bin"
    "${gnumake}/bin"
    "${tinycc.compiler}/bin"
    "${stage0.mescc-tools-extra.bin}/bin"
  ];

  CC = "${tinycc.compiler}/bin/tcc -static -B ${tinycc.libs}/lib -I ${mesInclude}";
  AR = "${tinycc.compiler}/bin/tcc -ar";

  builder = "${bash}/bin/bash";
  args = [
    "-e"
    ./build.sh
  ];

  meta = {
    description = "GNU sed, a batch stream editor";
    homepage = "https://www.gnu.org/software/sed";
    license = "gpl3Plus";
    inherit platforms;
  };
}
