# GNU bash 2.05b, compiled by tcc against ntlibc: the first real shell here.
#
# kaem got the chain this far -- it can run a program and substitute a
# variable, and nothing more.  Everything above wants a shell with variables,
# loops, conditionals and pipelines, which is what ./configure scripts are
# written in.  This is that shell.
#
# 2.05b for the same reason the Linux side picks it: it is the version
# live-bootstrap made build against a C library this small, and its makefiles
# and patches are reused here.  bash's own Makefiles are generated by a
# configure nothing in this bootstrap can run, so live-bootstrap's three
# hand-written ones stand in and config.h is made empty -- every answer
# configure would have written is a -D in build.kaem instead.
#
# Of live-bootstrap's five patches only three are taken.  The two that are
# not exist to work around the *Mes* C library, and ntlibc is not that
# library: mes-libc.patch and locale.patch both remove locale handling that
# ntlibc genuinely has.  The same is true of three -D in live-bootstrap's
# common.mk, which is why windows.patch's first hunk is a deletion -- see
# there.
{
  derivationWithMeta,
  stage0,
  tinycc,
  ntlibc,
  gnumake,
  gnupatch,
  callPackage,
}:
let
  pname = "bash";
  version = "2.05b";
  inherit (stage0) system platforms;

  tcc = tinycc.boot.tcc;

  # Both halves of ntlibc: the built library, and the source tree its headers
  # live in -- see the ntlibc package for why only one header is in the
  # output.
  ntlibcSrc = (callPackage ../ntlibc/bootstrap-sources.nix { }).src;

  # tcc's own runtime, for the 64-bit arithmetic helpers bash's `let' and
  # $((...)) need.  ntlibc does not carry it, and should not: it is the
  # compiler's, not the C library's.
  tccLibs = tinycc.boot.bootstrappable.libs;

  fetchurl = import <nix/fetchurl.nix>;

  # live-bootstrap, at the revision the Linux side pins -- the makefiles and
  # the patches have to come from one tree or the patches miss.
  liveBootstrap = "https://raw.githubusercontent.com/fosslinux/live-bootstrap/c0494d9af84b9e8c3e76e34c6e898978013a3b39/steps/bash-2.05b";

  fetchLiveBootstrap =
    { file, sha256 }:
    fetchurl {
      url = "${liveBootstrap}/${file}";
      name = baseNameOf file;
      inherit sha256;
    };
in
derivationWithMeta {
  inherit pname version system;

  # mirrors.kernel.org rather than ftp.gnu.org, which does not answer here.
  tarball = fetchurl {
    url = "https://mirrors.kernel.org/gnu/bash/bash-${version}.tar.gz";
    sha256 = "ba03d412998cc54bd0b0f2d6c32100967d3137098affdc2d32e6e7c11b163fe4";
  };

  mainmk = fetchLiveBootstrap {
    file = "mk/main.mk";
    sha256 = "448256e3a448718a3beddd24ed44dffe2cead2de77768dc205670c7c074e4242";
  };
  commonmk = fetchLiveBootstrap {
    file = "mk/common.mk";
    sha256 = "f41cd424fcfa571fabebd8b649096a4531fd8a180b694a752526069536d65aef";
  };
  builtinsmk = fetchLiveBootstrap {
    file = "mk/builtins.mk";
    sha256 = "92229aefd9ecb6a159cc4cac0bb3740994f9a81d861b297575b007bf8a6f6924";
  };

  # bash declares a struct field one way and tcc reads it another, so the
  # declaration is made to match.  Nothing to do with the C library.
  patchTinycc = fetchLiveBootstrap {
    file = "patches/tinycc.patch";
    sha256 = "42b227f35ed4b8ab0656a7a4394aaec466677287775318e657742245f2144d10";
  };
  # There is no /dev here either, so nothing can open /dev/tty.
  patchDevTty = fetchLiveBootstrap {
    file = "patches/dev-tty.patch";
    sha256 = "499632e597a3de7ef0359e04de0d68bc076795a792bceeb154f11f5736d5258c";
  };
  patchMissingDefines = fetchLiveBootstrap {
    file = "patches/missing-defines.patch";
    sha256 = "444e8b8f811e85616986bb5aee83876315554e29711e4f319e72e75ae40c13e0";
  };

  # Everything this side needs that live-bootstrap's patches do not cover, in
  # one file -- read its header for the reason behind each hunk.
  patchWindows = ./windows.patch;

  # Four headers and one function ntlibc does not have.  They are copied into
  # the source tree, where the makefiles' own -I. and -I.. already look, so
  # no store path has to reach the compiler for them.  Each says in its own
  # header comment what it stands in for; all five go away the day ntlibc
  # grows a terminal layer.
  shimTermio = ./termio.h;
  shimSysFile = ./sys-file.h;
  shimSysTimes = ./sys-times.h;
  shimSysIoctl = ./sys-ioctl.h;
  shimCompat = ./compat.c;

  # Run by build.kaem after --version, before install.  See the file.
  selftest = ./selftest.sh;

  inherit
    ntlibc
    tcc
    ntlibcSrc
    tccLibs
    ;

  # One argument each, because kaem substitutes a variable whole.
  #
  # The -D fall into three groups.  The first is what ./configure would have
  # discovered about ntlibc and live-bootstrap's common.mk does not say,
  # because mes-libc did not have any of it: strcasecmp, gethostname, uname,
  # getdtablesize, killpg, <stddef.h>, long long.
  #
  # The second is locale.  live-bootstrap builds bash with -DLC_ALL=\"C\" and
  # without -DHAVE_SETLOCALE, which together make every setlocale() call in
  # bash expand to nothing -- correct for a C library with no locale at all,
  # wrong here.  windows.patch removes the -D; these two put the real thing
  # back.
  #
  # The third is strsignal.  live-bootstrap says -DHAVE_SYS_SIGLIST, which
  # makes bash define sys_siglist itself; ntlibc has no such array but does
  # have strsignal(), so HAVE_STRSIGNAL is the honest answer.  It matters
  # more than it looks: without it siglist.h defines strsignal(sig) as a
  # function-like macro, which turns ntlibc's own `char *strsignal(int);'
  # into `char *(char *)sys_siglist[int];' the next time <string.h> is read.
  ccflag = "CC=${tcc} -B ${ntlibc}/lib -nostdinc -I${ntlibcSrc}/include -I${ntlibcSrc}/arch/i386 -I${ntlibcSrc}/arch/generic -I${ntlibc}/include -DHAVE_STRCASECMP -DHAVE_GETHOSTNAME -DHAVE_UNAME -DHAVE_GETDTABLESIZE -DHAVE_KILLPG -DHAVE_STDDEF_H -DHAVE_LONG_LONG -DHAVE_UNSIGNED_LONG_LONG -DHAVE_LOCALE_H -DHAVE_SETLOCALE -DHAVE_STRSIGNAL -DHAVE_DECL_STRSIGNAL=1";

  # This tcc's -ar takes no flag cluster -- see windows.patch.
  arflag = "AR=${tcc} -ar";

  # live-bootstrap's LDFLAGS is `-L. -Lbuiltins -static'.  -static means
  # nothing to a PE-target tcc, which adds neither a startup object nor a
  # default C library the way the ELF side does, so crt1.o is named outright
  # and -nostdlib keeps tcc from reaching for msvcrt and kernel32.
  ldflag = "LDFLAGS=-L. -Lbuiltins -nostdlib ${ntlibc}/lib/crt1.o";

  # And the libraries, deliberately NOT in LDFLAGS.  A PE tcc resolves each
  # archive in a single pass, in the order given, so anything that satisfies
  # bash's own libsh/libbuiltins/libglob/libtilde has to come after them --
  # LDFLAGS lands before.  With -lc first, getcwd, chdir and iscntrl go
  # unresolved.  windows.patch adds $(EXTRALIBS) at the end of every link
  # rule for exactly this.
  xlibflag = "EXTRALIBS=-L ${ntlibc}/lib -L ${tccLibs}/lib -lc -lntdll -ltcc1";

  bin_make = "${gnumake}/bin/make.exe";
  bin_patch = "${gnupatch}/bin/patch.exe";
  bin_ungz = stage0.mescc-tools-extra.ungz;
  bin_untar = stage0.mescc-tools-extra.untar;
  bin_catm = stage0.mescc-tools-extra.catm;
  bin_cp = stage0.mescc-tools-extra.cp;
  bin_mkdir = stage0.mescc-tools-extra.mkdir;

  builder = stage0.kaem;
  args = [
    "--verbose"
    "--strict"
    "--file"
    ./build.kaem
  ];

  meta = {
    description = "GNU Bourne-Again Shell, the de facto standard shell";
    homepage = "https://www.gnu.org/software/bash";
    license = "gpl3Plus";
    inherit platforms;
  };
}
