# GNU sed 4.0.9, compiled by the tcc this chain built, against ntlibc.
#
# The PE32 counterpart of ../../../linux/bootstrap/gnused.  Same version and
# same live-bootstrap revision: 4.0.9 is the last sed whose sources need no
# configure of their own, and the makefile comes from live-bootstrap because
# sed's own Makefile is generated by a configure that needs a sed to run.
# The tarball comes from mirrors.kernel.org rather than ftp.gnu.org, which
# does not answer here.
#
# Three things about this build are worth naming against its Linux twin.
#
# It is driven by kaem and make, not by bash.  The Linux package was the
# first there to use a shell script, because it wanted one variable holding
# a compiler and its flags.  Here every make variable is one kaem variable,
# the way gnumake and coreutils do it, so the shell buys nothing -- and one
# fewer dependency in a bootstrap is worth having.
#
# There are two sed builds on Linux and one here.  The Linux gnused-musl
# exists because sed compiled against Mes's C library gets getc and ungetc
# on stdin wrong: `$' matches the first line of a pipe, `N' ends the script,
# and every configure downstream then fails while writing its Makefile.
# ntlibc's stdio holds up, so the first sed built on this side is already
# the one that works -- verified on a pipe, not assumed.
#
# No patches at all, and no -U_WIN32.  coreutils needed -U_WIN32 -UWIN32
# because gnulib reads them as "the Win32 API is available" and reaches for
# <windows.h>; sed 4.0.9 predates gnulib and tests WIN32 in exactly one
# place, an alloca fallback that HAVE_ALLOCA_H already skips over.  Taking
# the defines away would have been a workaround for nothing.
{
  stdenv,
  stage0,
  tinycc,
  ntlibc,
  gnumake,
  callPackage,
}:
let
  pname = "gnused";
  version = "4.0.9";
  inherit (stage0) system platforms;
  ntlibcSources = callPackage ../../../nt/ntlibc/bootstrap-sources.nix { };

  fetchurl = import <nix/fetchurl.nix>;
in
stdenv.mkDerivation {
  inherit pname version system;

  tarball = fetchurl {
    url = "https://mirrors.kernel.org/gnu/sed/sed-${version}.tar.gz";
    sha256 = "c365874794187f8444e5d22998cd5888ffa47f36def4b77517a808dec27c0600";
  };

  # sed's own Makefile comes from a configure script that needs a sed to
  # run, so the makefile comes from live-bootstrap -- at the revision the
  # Linux package pins.
  makefile = fetchurl {
    url = "https://raw.githubusercontent.com/fosslinux/live-bootstrap/1bc4296091c51f53a5598050c8956d16e945b0f5/sysa/sed-4.0.9/mk/main.mk";
    name = "main.mk";
    sha256 = "cad7c18d085399d640e23a7feb70b36a378ed7f7dd5053c350f49707622e2e70";
  };

  make = "${gnumake}/bin/make.exe";
  tcc = tinycc.boot.tcc;

  # Both halves of ntlibc: the built libraries, and the source tree its
  # headers live in.  Only bits/alltypes.h is generated, and that one is in
  # the output beside the libraries -- see the ntlibc package.
  inherit ntlibc;
  ntlibcSrc = ntlibcSources.src;

  # What ./configure would have discovered.  See the head of the file for
  # why it is a header and not a wall of -D.
  configH = ./config.h;

  # One kaem variable per make variable, because kaem substitutes a variable
  # as a single argument: written out, `CC=tcc -B .../lib' would reach make
  # as two.  These override the makefile's own assignments, which name a
  # bare `tcc' and a Linux link line.
  #
  # HAVE_CONFIG_H is the only -D left on the command line: sed/sed.h and
  # lib/obstack.h include <config.h> only when told to.
  #
  # LIBC picks a branch in the makefile.  Anything but "mes" is the branch
  # for a library that has getline already, which ntlibc does; naming the
  # library rather than "musl" is only honesty about which one it is.
  ccflag = "CC=${tinycc.boot.tcc}";
  arflag = "AR=${tinycc.boot.tcc} -ar";
  libcflag = "LIBC=ntlibc";
  cppflags = "CPPFLAGS=-DHAVE_CONFIG_H";
  cflags = "CFLAGS=-nostdinc -I. -Ilib -I${ntlibcSources.src}/include -I${ntlibcSources.src}/arch/i386 -I${ntlibcSources.src}/arch/generic -I${ntlibc}/include -B ${ntlibc}/lib";

  # A PE-target tcc adds neither a startup object nor a default C library
  # the way the ELF side does, and the default it does reach for (msvcrt,
  # kernel32) is not what this bootstrap has, so crt1.o and -lc/-lntdll are
  # named outright -- ntdll.def being the import library ntlibc resolves its
  # kernel calls through.  The Linux build's -static has no meaning here.
  #
  # -lsed stays first, as the makefile has it: a linker that resolves
  # archives in one pass must see the package's own archive before the C
  # library, or sed's regcomp and obstack go unresolved.
  ldflags = "LDFLAGS=-L. -lsed -nostdlib ${ntlibc}/lib/crt1.o -L ${ntlibc}/lib -lc -lntdll";

  # Three one-line edits to the fetched makefile.  See build.kaem.
  arPattern = "$(AR) cr $@ $^";
  arReplacement = "$(AR) $@ $^";
  allocaPattern = "LIB_SRC = alloca";
  allocaReplacement = "LIB_SRC = utils";
  libsrcPattern = "LIB_SRC += getopt1 getopt utils regex obstack strverscmp mkstemp";
  libsrcReplacement = "LIB_SRC += regex obstack";

  bin_ungz = stage0.mescc-tools-extra.ungz;
  bin_untar = stage0.mescc-tools-extra.untar;
  bin_cp = stage0.mescc-tools-extra.cp;
  bin_mkdir = stage0.mescc-tools-extra.mkdir;
  bin_replace = stage0.mescc-tools-extra.replace;

  builder = stage0.kaem;
  args = [
    "--verbose"
    "--strict"
    "--file"
    ./build.kaem
  ];

  meta = {
    description = "GNU sed, a batch stream editor";
    homepage = "https://www.gnu.org/software/sed";
    license = "gpl3Plus";
    inherit platforms;
  };
}
