# GNU sed 4.0.9, compiled by tcc.
#
# The first package here built by a shell script rather than a kaem file.
# 4.0.9 is the last version that compiles against the Mes C library, and its
# own Makefile is generated by a configure that needs a sed to run -- so the
# makefile comes from live-bootstrap instead.
{
  stdenv,
  system,
  platforms,
  stage0,
  tinycc,
  gnumake,
  bash,
  coreutils,
  mesInclude,
}:
let
  pname = "gnused";

  sources = import ./sources.nix { };
  inherit (sources) version;
in
stdenv.mkDerivation {
  inherit pname version system;

  tarball = sources.src;
  inherit (sources) makefile;

  # What the script may run.  This replaces the PATH the builder would
  # otherwise assemble, which includes the host's /usr/bin.
  toolPath = builtins.concatStringsSep ":" [
    "${coreutils}/bin"
    "${gnumake}/bin"
    "${tinycc.compiler}/bin"
    "${stage0.mescc-tools-extra.bin}/bin"
  ];

  libc = "mes";

  CC = "${tinycc.compiler}/bin/tcc -static -B ${tinycc.libs}/lib -I ${mesInclude}";
  AR = "${tinycc.compiler}/bin/tcc -ar";

  builder = "${bash}/bin/bash";
  args = [
    "-e"
    ./build.sh
  ];

  meta = {
    description = "GNU sed, a batch stream editor";
    homepage = "https://www.gnu.org/software/sed";
    license = "gpl3Plus";
    inherit platforms;
  };
}
