# The Mes C library, compiled by MesCC.
#
# mes-m2 is the interpreter the chain below produced; MesCC is the C compiler
# written in Scheme that it runs, parsing C with Nyacc, emitting M1 assembly,
# and spawning M1 and hex2 to assemble and link.  This is the first thing in
# the bootstrap compiled by Mes rather than by M2-Planet, and it is what
# TinyCC will link against.
#
# Each library is a single translation unit: catm concatenates its sources in
# upstream's order -- which is load-bearing, since a definition has to come
# before whatever uses it -- and MesCC compiles the result in one go.  There
# is no separate compilation and no linker to resolve between objects, which
# is why the lists run to a hundred files and more.
#
# Those lists are too long to reach a build through the environment: kaem's
# MAX_STRING is 4096 characters and a hundred store paths is twice that.  So
# the concatenation and the compiling are derivations, where nova-nix spawns
# the process with an argument vector and no such limit applies.  kaem is left
# with the two jobs that genuinely need a shell: making a directory.
{
  derivationWithMeta,
  src,
  version,
  system,
  platforms,
  kaem,
  mes-m2,
  nyacc,
  stage0,
}:
let
  arch = "x86";
  sources = import ./libc-sources.nix { };
  out = builtins.placeholder "out";

  inherit (stage0.mescc-tools-extra) mkdir cp catm;

  meta = {
    description = "The Mes C library, compiled by MesCC";
    homepage = "https://www.gnu.org/software/mes/";
    license = "gpl3Plus";
    inherit platforms;
  };

  configH = builtins.toFile "config.h" ''
    #undef SYSTEM_LIBC
    #define MES_VERSION "${version}"
  '';

  # A -I wants a directory, so config.h gets one of its own.
  configInclude = derivationWithMeta {
    pname = "mes-config-include";
    inherit version system meta;
    bin_mkdir = mkdir;
    bin_cp = cp;
    inherit configH src arch;
    builder = kaem;
    args = [
      "--verbose"
      "--strict"
      "--file"
      ./libc-include.kaem
    ];
  };

  # scripts/mescc.scm is generated by ./configure from a template.  Nothing
  # here runs configure, so the two definitions it would substitute are
  # prepended instead -- see mescc-prelude.scm.
  mescc = derivationWithMeta {
    pname = "mescc.scm";
    inherit version system meta;
    builder = catm;
    args = [
      out
      ./mescc-prelude.scm
      "${src}/scripts/mescc.scm.in"
    ];
  };

  # One translation unit, concatenated from upstream's list.
  #
  # The store path has to END in .c: MesCC decides what to do with an input by
  # its suffix, and anything that is not .c or .E it takes for an object file
  # and hands to the linker.  A bundle named otherwise compiles to nothing at
  # all, and MesCC exits successfully having written no output.
  bundle =
    name: files:
    derivationWithMeta {
      pname = "mes-${name}";
      name = "mes-${name}-${version}.c";
      inherit version system meta;
      builder = catm;
      args = [ out ] ++ map (f: "${src}/${f}") files;
    };

  # MesCC, as a derivation: the interpreter is the builder, the driver and the
  # include path are arguments, and M1 and hex2 are named in the environment
  # rather than found on PATH -- mescc.scm reads (or (getenv "M1") "M1") --
  # so no bin directory has to exist yet.
  # base is the library's name, suffix what it is being compiled to.  The
  # store path has to END in that suffix: MesCC decides what an input is by
  # it, and takes anything that is not .c, .E or .s for an object file -- so
  # a .s that is not named .s links to nothing, silently and successfully.
  mescc-compile =
    base: suffix: mode: input:
    derivationWithMeta {
      pname = "mes-${base}${suffix}";
      name = "mes-${base}-${version}${suffix}";
      inherit version system meta;

      # Mes sizes its heap and its stack from the environment, and the
      # defaults are not enough for a translation unit of this size: libc+tcc
      # is 159 files concatenated into one, and compiling it segfaults on the
      # default arena.  These are the numbers nixpkgs' minimal bootstrap
      # patches into gc.c for the same reason.
      MES_ARENA = "100000000";
      MES_MAX_ARENA = "100000000";
      MES_STACK = "6000000";

      MES_PREFIX = "${src}";
      GUILE_LOAD_PATH = "${src}/mes/module:${src}/module:${nyacc.guilePath}";
      M1 = stage0.M1;
      HEX2 = stage0.hex2;
      BLOOD_ELF = stage0.blood_elf_0;

      builder = mes-m2;
      args = [
        "-e"
        "main"
        "${mescc}"
        "--"
        mode
        "-D"
        "HAVE_CONFIG_H=1"
        # First, so the config.h written above wins the name.
        "-I"
        "${configInclude}"
        "-I"
        "${src}/include"
        "-I"
        "${src}/include/linux/${arch}"
        "-o"
        out
        "${input}"
      ];
    };

  # Every library is shipped twice over, and both forms are used.  MesCC
  # LINKS from assembly -- hex2 is the linker, and it reads .s -- so `-l c+tcc`
  # looks for libc+tcc.s.  tcc, once it exists, links objects, and reads the
  # .a.  Upstream builds both for the same reason.
  compiled = name: source: rec {
    s = mescc-compile name ".s" "-S" source;
    a = mescc-compile name ".a" "-c" s;
  };

  # The same library in source form, for a compiler that is not MesCC.  tcc,
  # once it exists, recompiles its own C library from these -- from the
  # gcc-variant sources, which are the fuller set MesCC could not manage.
  gnuSource = {
    libc = bundle "libc+gnu" sources.libc_gnu_SOURCES;
    libtcc1 = bundle "libtcc1" sources.libtcc1_SOURCES;
    crt1 = "${src}/lib/linux/${arch}-mes-gcc/crt1.c";
    crti = "${src}/lib/linux/${arch}-mes-gcc/crti.c";
    crtn = "${src}/lib/linux/${arch}-mes-gcc/crtn.c";
    getopt = "${src}/lib/posix/getopt.c";
  };

  crt1-s = mescc-compile "crt1" ".s" "-S" "${src}/lib/linux/${arch}-mes-mescc/crt1.c";
  crt1 = mescc-compile "crt1" ".o" "-c" crt1-s;

  libc-mini = compiled "libc-mini" (bundle "libc-mini" sources.libc_mini_SOURCES);
  libmescc = compiled "libmescc" (bundle "libmescc" sources.libmescc_SOURCES);
  libc = compiled "libc" (bundle "libc" sources.libc_SOURCES);
  libc-tcc = compiled "libc+tcc" (bundle "libc+tcc" sources.libc_tcc_SOURCES);
in
derivationWithMeta {
  pname = "mes-libc";
  inherit version system meta;

  inherit src arch;
  bin_mkdir = mkdir;
  bin_cp = cp;

  inherit crt1 mescc;
  crt1_s = crt1-s;
  libc_mini_a = libc-mini.a;
  libc_mini_s = libc-mini.s;
  libmescc_a = libmescc.a;
  libmescc_s = libmescc.s;
  libc_a = libc.a;
  libc_s = libc.s;
  libc_tcc_a = libc-tcc.a;
  libc_tcc_s = libc-tcc.s;

  builder = kaem;
  args = [
    "--verbose"
    "--strict"
    "--file"
    ./libc-out.kaem
  ];

  passthru = {
    # What a caller has to repeat to compile against this library: the same
    # include path MesCC was given here.
    CFLAGS = [
      "-D"
      "HAVE_CONFIG_H=1"
      "-I"
      "${configInclude}"
      "-I"
      "${src}/include"
      "-I"
      "${src}/include/linux/${arch}"
    ];

    inherit gnuSource;

    inherit
      crt1
      crt1-s
      libc-mini
      libmescc
      libc
      libc-tcc
      mescc
      configInclude
      ;
  };
}
