# GNU coreutils 5.0, compiled by the tcc this chain built, against ntlibc.
#
# The PE32 counterpart of ../../../linux/bootstrap/coreutils, and the first
# package on this side that make drives rather than kaem: cp, mv, rm, mkdir,
# cat, ls, sort and the rest, which every build script above here assumes.
#
# Same version and same live-bootstrap revision as the Linux package: 5.0
# because later coreutils want gnulib and a working locale, and the makefile
# because coreutils' own Makefile.in is generated by a configure nothing here
# can run.  The tarball comes from mirrors.kernel.org rather than ftp.gnu.org,
# which does not answer here.
#
# Seven of the Linux build's eight patches are gone.  Every one of them says
# something about the Mes C library that is not true of ntlibc:
#
#   modechange        modechange.h ahead of <sys/stat.h>.  ntlibc's
#                     <sys/stat.h> is reached through system.h either way.
#   mbstate           mbstate_t, which ntlibc has in <wchar.h>.
#   ls-strcmp         strcoll, which ntlibc has.
#   expr-strcmp       the same.
#   sort-locale       strcoll again, plus hard_LC_COLLATE being used with
#                     HAVE_SETLOCALE unset.  ntlibc has setlocale, so it is
#                     set and the declaration is in the branch taken.
#   uniq-fopen        a real bug, fixed upstream in 2005, but not one that
#                     stops this from building or from running correctly on
#                     the inputs a bootstrap gives it.
#   touch-dereference a backport of touch -h.  A feature, not a fix.
#
# What remains is touch-getdate, which is not about the C library at all --
# lib/getdate.c cannot be compiled by anything here, and nothing regenerates
# it, so `touch -d' has to lose its argument parser -- and one patch of our
# own, for a FILE that ntlibc quite correctly refuses to give a size to.
{
  derivationWithMeta,
  stage0,
  tinycc,
  ntlibc,
  gnumake,
  gnupatch,
  callPackage,
}:
let
  pname = "coreutils";
  version = "5.0";
  inherit (stage0) system platforms;
  ntlibcSources = callPackage ../../../nt/ntlibc/bootstrap-sources.nix { };

  fetchurl = import <nix/fetchurl.nix>;

  # live-bootstrap, at the revision the Linux package pins.
  liveBootstrap = "https://raw.githubusercontent.com/fosslinux/live-bootstrap/a8752029f60217a5c41c548b16f5cdd2a1a0e0db/sysa/coreutils-5.0";
in
derivationWithMeta {
  inherit pname version system;

  tarball = fetchurl {
    url = "https://mirrors.kernel.org/gnu/coreutils/coreutils-${version}.tar.gz";
    sha256 = "c27ce75e3f62455f4facf4f3fd55bc9e3877d0ab1d5c0426c94da168cc349883";
  };

  makefile = fetchurl {
    url = "${liveBootstrap}/mk/main.mk";
    name = "main.mk";
    sha256 = "cdd19bf9679b3aa458e57d5b417aabce5268e0d1142d5a33d519bbce58274f5a";
  };

  # getdate.c is shipped pre-generated and does not compile here; there is no
  # bison yet, and a modern one does not produce something that would.  The
  # makefile leaves it out of the library, so touch's one call to get_date has
  # to go too or touch does not link.
  patchGetdate = fetchurl {
    url = "${liveBootstrap}/patches/touch-getdate.patch";
    name = "touch-getdate.patch";
    sha256 = "aa12123cff7d49657519a39d282f2ad7d3df595a10d8a237ca47ce4d4ff9a3f5";
  };

  # Ours, not live-bootstrap's: see the file.
  patchPaste = ./patches/paste-opaque-file.patch;

  make = "${gnumake}/bin/make.exe";
  patch = "${gnupatch}/bin/patch.exe";

  # Both halves of ntlibc: the built libraries, and the source tree its
  # headers live in.  Only bits/alltypes.h is generated, and that one is in
  # the output beside the libraries -- see the ntlibc package.
  inherit ntlibc;
  ntlibcSrc = ntlibcSources.src;

  # What configure would have discovered, and the two headers that stand in
  # for what ntlibc does not have.  See each file.
  configH = ./config.h;
  shimGrp = ./shim/grp.h;
  shimIoctl = ./shim/sys/ioctl.h;

  # One kaem variable per make variable, because kaem substitutes a variable
  # as a single argument: written out, `CC=tcc -B .../lib' would reach make
  # as two.  These override the makefile's own assignments, which name a bare
  # `tcc' and a Linux link line.
  #
  # -U_WIN32 -UWIN32 because a PE-target tcc defines both, and gnulib reads
  # them as "this is the Win32 API": localcharset.c and physmem.c then reach
  # for <windows.h> and GetACP/GlobalMemoryStatusEx.  None of that is here.
  # ntlibc is the NT system-call layer, not Win32, and its own headers never
  # test either name, so taking them away leaves the POSIX branches -- which
  # are the ones ntlibc implements.
  #
  # -DHAVE_CONFIG_H because coreutils' lib/*.c include <config.h> only when
  # told to; src/*.c include it unconditionally.
  ccflag = "CC=${tinycc.boot.tcc}";
  ldflag = "LD=${tinycc.boot.tcc}";
  arflag = "AR=${tinycc.boot.tcc} -ar";
  cflags = "CFLAGS=-DHAVE_CONFIG_H -U_WIN32 -UWIN32 -nostdinc -I. -Ilib -Ishim -I${ntlibcSources.src}/include -I${ntlibcSources.src}/arch/i386 -I${ntlibcSources.src}/arch/generic -I${ntlibc}/include -B ${ntlibc}/lib";

  # A PE-target tcc adds neither a startup object nor a default C library the
  # way the ELF side does, and the default it does reach for (msvcrt,
  # kernel32) is not what this bootstrap has, so crt1.o and -lc/-lntdll are
  # named outright -- ntdll.def being the import library ntlibc resolves its
  # kernel calls through.  The Linux build's -static has no meaning here.
  #
  # This lands after the package's own libfettish.a on every link line the
  # makefile writes, which is what a linker that resolves archives in one
  # pass needs.
  ldflags = "LDFLAGS=-nostdlib ${ntlibc}/lib/crt1.o -L ${ntlibc}/lib -lc -lntdll";

  # Four edits to the fetched makefile, each one line.  See build.kaem.
  arPattern = "$(AR) cr $@ $^";
  arReplacement = "$(AR) $@ $^";
  getlinePattern = "getline getstr";
  getlineReplacement = "getstr";
  strtoimaxPattern = "strtoimax strtoumax umaxtostr";
  strtoimaxReplacement = "umaxtostr";
  dirfdPattern = "ftw dirfd obstack";
  dirfdReplacement = "ftw obstack";

  bin_ungz = stage0.mescc-tools-extra.ungz;
  bin_untar = stage0.mescc-tools-extra.untar;
  bin_cp = stage0.mescc-tools-extra.cp;
  bin_mkdir = stage0.mescc-tools-extra.mkdir;
  bin_replace = stage0.mescc-tools-extra.replace;

  builder = stage0.kaem;
  args = [
    "--verbose"
    "--strict"
    "--file"
    ./build.kaem
  ];

  meta = {
    description = "GNU core utilities";
    homepage = "https://www.gnu.org/software/coreutils";
    license = "gpl3Plus";
    inherit platforms;
  };
}
