# The Mes C library, compiled by MesCC.
#
# Shared by every package set.  What the library is made of is decided by
# build-aux/configure-lib.sh in the Mes tree, which reads mes_kernel and picks
# a different set of files for each; that decision arrives here as `sources`,
# and the rest of this file is the same work whichever set it was.  Where the
# two kernels genuinely differ -- what a program starts at, and what a linker
# has to put around it -- there is an `if windows` below and a note saying
# why.
#
# mes-m2 is the interpreter the chain below produced; MesCC is the C compiler
# written in Scheme that it runs, parsing C with Nyacc, emitting M1 assembly,
# and spawning M1 and hex2 to assemble and link.  This is the first thing in
# the bootstrap compiled by Mes rather than by M2-Planet, and it is what
# TinyCC will link against.
#
# Each library is a single translation unit: catm concatenates its sources in
# upstream's order -- which is load-bearing, since a definition has to come
# before whatever uses it -- and MesCC compiles the result in one go.  There
# is no separate compilation and no linker to resolve between objects, which
# is why the lists run to a hundred files and more.
#
# Those lists are too long to reach a build through the environment: kaem's
# MAX_STRING is 4096 characters and a hundred store paths is twice that.  So
# the concatenation and the compiling are derivations, where nova-nix spawns
# the process with an argument vector and no such limit applies.  kaem is left
# with the two jobs that genuinely need a shell: making a directory.
{
  lib,
  derivationWithMeta,
  src,
  version,
  system,
  platforms,
  kaem,
  mes-m2,
  nyacc,
  stage0,
  # The kernel this library is for, spelled as Mes spells it: it names the
  # include and lib subdirectories, and it decides the two things below that
  # are not shared.
  mesKernel,
  # The source lists, as configure-lib.sh computes them for that kernel.
  # Kept with the package set it belongs to, since it is that kernel's data.
  sources,
  # The two definitions scripts/mescc.scm.in expects to already exist, one of
  # which is the kernel -- so this is per-kernel too.  See the file.
  mesccPrelude,
  arch ? "x86",
  # How many cells Mes may have, which is what MES_ARENA counts -- a cell is
  # twelve bytes here, plus a tenth again for the jam buffer.  100000000 is
  # nixpkgs' number for the same reason it patches gc.c: a translation unit of
  # 159 files does not compile in less.
  #
  # It is a call-site argument because it is not always available.  A Linux
  # Mes asks the kernel for 1.3GB and gets it; a Windows one reserves address
  # space with NtAllocateVirtualMemory and gets what a 32-bit process can hold
  # in one piece, which is a gigabyte on Windows 11 and 256MB under wine.  See
  # lib/windows/brk.c, which discovers the figure rather than declaring it.
  arenaSize ? "100000000",
}:
let
  out = builtins.placeholder "out";
  windows = mesKernel == "windows";

  inherit (stage0.mescc-tools-extra) mkdir cp catm;

  meta = {
    description = "The Mes C library, compiled by MesCC";
    homepage = "https://www.gnu.org/software/mes/";
    license = "gpl3Plus";
    inherit platforms;
  };

  configH = builtins.toFile "config.h" ''
    #undef SYSTEM_LIBC
    #define MES_VERSION "${version}"
  '';

  # A -I wants a directory, so config.h gets one of its own.
  configInclude = derivationWithMeta {
    pname = "mes-config-include";
    inherit version system meta;
    bin_mkdir = mkdir;
    bin_cp = cp;
    inherit configH src arch;
    archInclude = "${src}/include/${mesKernel}/${arch}";
    builder = kaem;
    args = [
      "--verbose"
      "--strict"
      "--file"
      ./libc-include.kaem
    ];
  };

  # scripts/mescc.scm is generated by ./configure from a template.  Nothing
  # here runs configure, so the two definitions it would substitute are
  # prepended instead -- see mescc-prelude.scm.
  mescc = derivationWithMeta {
    pname = "mescc.scm";
    inherit version system meta;
    builder = catm;
    args = [
      out
      mesccPrelude
      "${src}/scripts/mescc.scm.in"
    ];
  };

  # One translation unit, concatenated from upstream's list.
  #
  # The store path has to END in .c: MesCC decides what to do with an input by
  # its suffix, and anything that is not .c or .E it takes for an object file
  # and hands to the linker.  A bundle named otherwise compiles to nothing at
  # all, and MesCC exits successfully having written no output.
  bundle =
    name: files:
    derivationWithMeta {
      pname = "mes-${name}";
      name = "mes-${name}-${version}.c";
      inherit version system meta;
      builder = catm;
      args = [ out ] ++ files;
    };

  # A source list is written relative to the Mes tree; a file from anywhere
  # else arrives already absolute.
  inTree = map (f: "${src}/${f}");

  # MesCC, as a derivation: the interpreter is the builder, the driver and the
  # include path are arguments, and M1 and hex2 are named in the environment
  # rather than found on PATH -- mescc.scm reads (or (getenv "M1") "M1") --
  # so no bin directory has to exist yet.
  # base is the library's name, suffix what it is being compiled to.  The
  # store path has to END in that suffix: MesCC decides what an input is by
  # it, and takes anything that is not .c, .E or .s for an object file -- so
  # a .s that is not named .s links to nothing, silently and successfully.
  mescc-compile =
    base: suffix: mode: input:
    derivationWithMeta {
      pname = "mes-${base}${suffix}";
      name = "mes-${base}-${version}${suffix}";
      inherit version system meta;

      # Mes sizes its heap and its stack from the environment, and the
      # defaults are not enough for a translation unit of this size: libc+tcc
      # is 159 files concatenated into one, and compiling it segfaults on the
      # default arena.
      MES_ARENA = arenaSize;
      MES_MAX_ARENA = arenaSize;
      MES_STACK = "6000000";

      MES_PREFIX = "${src}";
      GUILE_LOAD_PATH = "${src}/mes/module:${src}/module:${nyacc.guilePath}";
      M1 = stage0.M1;
      # mescc.scm passes flags, so this is the C-written hex2 rather than the
      # early hand-written linker on either platform.
      HEX2 = stage0.hex2;

      builder = mes-m2;
      args = [
        "-e"
        "main"
        "${mescc}"
        "--"
        mode
        "-D"
        "HAVE_CONFIG_H=1"
        # First, so the config.h written above wins the name.
        "-I"
        "${configInclude}"
        "-I"
        "${src}/include"
        "-I"
        "${src}/include/${mesKernel}/${arch}"
        "-o"
        out
        "${input}"
      ];
    };

  # Every library is shipped twice over, and both forms are used.  MesCC
  # LINKS from assembly -- hex2 is the linker, and it reads .s -- so `-l c+tcc`
  # looks for libc+tcc.s.  tcc, once it exists, links objects, and reads the
  # .a.  Upstream builds both for the same reason.
  compiled = name: source: rec {
    s = mescc-compile name ".s" "-S" source;
    a = mescc-compile name ".a" "-c" s;
  };

  # The same library in source form, for a compiler that is not MesCC.  tcc,
  # once it exists, recompiles its own C library from these -- from the
  # gcc-variant sources, which are the fuller set MesCC could not manage.
  #
  # Only ELF has the crt pieces: crti and crtn exist to bracket .init and
  # .fini, which is a thing the ELF linker does with sections and the PE one
  # does not.  A Windows entry point is crt1 and nothing else.
  gnuSource = {
    libc = bundle "libc+gnu" (inTree sources.libc_gnu_SOURCES);
    libtcc1 = bundle "libtcc1" (inTree sources.libtcc1_SOURCES);
    getopt = "${src}/lib/posix/getopt.c";
  }
  // lib.optionalAttrs (!windows) {
    crt1 = "${src}/lib/linux/${arch}-mes-gcc/crt1.c";
    crti = "${src}/lib/linux/${arch}-mes-gcc/crti.c";
    crtn = "${src}/lib/linux/${arch}-mes-gcc/crtn.c";
  };

  # What runs before main, which is the one part of a C library that cannot be
  # written portably and, on Windows, cannot be written in C at all.
  #
  # On Linux the kernel has already put argc, argv and the environment on the
  # stack, so crt1.c is a dozen lines of moving them into place and MesCC
  # compiles it like anything else.  Windows passes one UTF-16 command line
  # and nothing else: splitting it is assembly, it runs before there is a
  # stdin to report a failure on, and it is shared with the M2-Planet build
  # that already needed it -- so it is three .M1 files, assembled here rather
  # than compiled.
  #
  # M1 is given both macro files.  A DEFINE is global to an assembly and the
  # startup uses both dialects' names: x86_defs.M1 is what M2-Planet emits and
  # x86.M1 is what MesCC emits, and the Windows files were written against the
  # first.
  windowsCrt1 = derivationWithMeta {
    pname = "mes-crt1";
    name = "mes-crt1-${version}.o";
    inherit version system meta;
    builder = stage0.M1;
    args = [
      "--architecture"
      arch
      "--little-endian"
      "-f"
      "${src}/lib/m2/x86/x86_defs.M1"
      "-f"
      "${src}/lib/${arch}-mes/x86.M1"
      "-f"
      "${src}/lib/windows/${arch}-mes/defs.M1"
      "-f"
      "${src}/lib/windows/${arch}-mes/argv.M1"
      "-f"
      "${src}/lib/windows/${arch}-mes-mescc/crt1.M1"
      "-o"
      out
    ];
  };

  # What hex2 puts around the program to make it an executable.  hex2 has no
  # idea what a format is: these two files are the whole of it, and mescc.scm
  # reaches for the pair whose name its kernel implies.
  #
  # The header is two files concatenated because hex2 is given exactly one and
  # the Windows one is genuinely two things: the PE header, and the code that
  # finds ntdll and resolves what the program will call out of its export
  # table.  A PE32 program from this bootstrap imports nothing at all, so that
  # resolver has to be inside the image.
  pe32Header = derivationWithMeta {
    pname = "mes-pe32-header.hex2";
    name = "mes-pe32-header-${version}.hex2";
    inherit version system meta;
    builder = catm;
    args = [
      out
      "${src}/lib/m2/x86/PE32-i386.hex2"
      "${src}/lib/m2/x86/ntdll-i386.hex2"
    ];
  };

  crt1-s = mescc-compile "crt1" ".s" "-S" "${src}/lib/linux/${arch}-mes-mescc/crt1.c";
  crt1 = if windows then windowsCrt1 else mescc-compile "crt1" ".o" "-c" crt1-s;

  libc-mini = compiled "libc-mini" (bundle "libc-mini" (inTree sources.libc_mini_SOURCES));
  libmescc = compiled "libmescc" (bundle "libmescc" (inTree sources.libmescc_SOURCES));
  libc = compiled "libc" (bundle "libc" (inTree sources.libc_SOURCES));
  libc-tcc = compiled "libc+tcc" (bundle "libc+tcc" (inTree sources.libc_tcc_SOURCES));
in
derivationWithMeta {
  pname = "mes-libc";
  inherit version system meta;

  inherit src arch;
  bin_mkdir = mkdir;
  bin_cp = cp;

  inherit crt1 mescc;
  # The assembly the startup was linked from, kept beside it the way every
  # library here is kept in both forms.  On Linux that is what MesCC emitted;
  # on Windows the .M1 is the source, and there is nothing it was emitted
  # from.
  crt1_s = if windows then "${src}/lib/windows/${arch}-mes-mescc/crt1.M1" else crt1-s;
  libc_mini_a = libc-mini.a;
  libc_mini_s = libc-mini.s;
  libmescc_a = libmescc.a;
  libmescc_s = libmescc.s;
  libc_a = libc.a;
  libc_s = libc.s;
  libc_tcc_a = libc-tcc.a;
  libc_tcc_s = libc-tcc.s;

  # The format's header and footer, installed under the name mescc.scm will
  # look for and the kernel directory it will look in.  Only Windows: the ELF
  # pair is already in the Mes tree, which is on the library path anyway.
  inherit mesKernel;
  pe32_header = if windows then pe32Header else "";
  pe32_footer = if windows then "${src}/lib/windows/${arch}-mes/pe-end.M1" else "";

  builder = kaem;
  args = [
    "--verbose"
    "--strict"
    "--file"
    (if windows then ./libc-out-windows.kaem else ./libc-out.kaem)
  ];

  passthru = {
    # What a caller has to repeat to compile against this library: the same
    # include path MesCC was given here.
    CFLAGS = [
      "-D"
      "HAVE_CONFIG_H=1"
      "-I"
      "${configInclude}"
      "-I"
      "${src}/include"
      "-I"
      "${src}/include/${mesKernel}/${arch}"
    ];

    inherit gnuSource;

    inherit
      crt1
      libc-mini
      libmescc
      libc
      libc-tcc
      mescc
      configInclude
      ;
  }
  // lib.optionalAttrs (!windows) { inherit crt1-s; }
  // lib.optionalAttrs windows {
    # What a caller has to hand hex2 to link a PE32 executable, for anything
    # that links one without going through mescc.scm.
    inherit pe32Header;
    pe32Footer = "${src}/lib/windows/${arch}-mes/pe-end.M1";
  };
}
